#!/bin/bash

#update package lists
apt-get update

#install nginx
apt-get install -y nginx

#create hello world HTML file
echo "Hello world!" > /var/www/html/index.html

#ensure listening on port 80
sed -i 's/#listen\ [\:\]*80;/listen 80;/' /etc/nginx/sites-available/default

#Restart nginx without systemctl
nginx -s stop
nginx

#open port 80 in firewall
ufw allow 80
