#!/usr/bin/env bash
#update package lists
apt-get -y update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start
# Optionally, open port 80 in the firewall (if enabled)
ufw allow 80