#!/usr/bin/env bash
#update package lists
apt-get update

#install nginx
apt-get install -y nginx

#create hello world HTML file
echo "Hello world!" > /var/www/html/index.html

ufw allow 'Nginx HTTP'

service nginx start
