#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
line="\\\trewrite ^/redirect_me http://kiptoobarchok.tech permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
