#!/usr/bin/env bash
# Configures a new ubuntu machine by installing

# Update package information
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create custom 404 page
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload  
