#!/usr/bin/env bash
# configure nginx to have custom HTTP response HEADER

#install nginx

sudo apt-get update
sudo apt-get -y install nginx


#custom nginx configurartion
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom_header.conf
sudo service nginx restart


# check if custom header is present
response=$(curl -sI http://localhost | grep -i 'X-Served-By')

# Print 1 if the custom header is present, otherwise print 0
if [ -n "$response" ]; then
    echo "1"
else
    echo "0"
fi
