#!/usr/bin/env bash
#configure Niginx to include custom HTTP response header

# install nginx 
sudo apt-get update
sudo apt-get -y install nginx

#create custom nginx configuration file
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom_header.conf

#Restart nginx
sudo service nginx restart

#check if custom header is present
response=$(curl -sI http://localhost | grep -i 'X-Served-By')

if [ -n "$response" ]; then
    echo "1"
else
    echo "0"
fi
