#!/usr/bin/env bash
#script to install a load balancer - HAProxy and configure it


sudo apt-get update -y
sudo apt upgrade
sudo apt-get -y install haproxy

echo "ENABLED" >> /etc/default/haproxy

echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web-01 54.237.114.20 check
        server web-02 54.210.50.93 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start