#!/usr/bin/env bash
# script to write hours 0- 12 and mins 1 - 59
#using while loop

hr=0

while [ $hr -le 12 ]
do
    echo "Hour: $hr"
    min=1
    while [ $min -le 59 ]
    do
    echo "$min"
    ((min++))
    done
    ((hr++))
done
